export const ActionTypes = {
    GET_ALL_ACCOUNT_COSTS: 'GET_ALL_ACCOUNT_COSTS',
    REMOVE_TS_COST_ITEM: 'REMOVE_TS_COST_ITEM',
    SET_COST_TOTAL: 'SET_COST_TOTAL',
    SET_COST_ITEM_LIST: 'SET_COST_ITEM_LIST',
    SET_SELECTED_COST_TSE_ITEMS: 'SET_SELECTED_COST_TSE_ITEMS',
    REMOVE_SELECTED_COST_TSE_ITEMS: 'REMOVE_SELECTED_COST_TSE_ITEMS',
    REMOVE_ITEM_COST_ITEM_LIST: 'REMOVE_ITEM_COST_ITEM_LIST',
};
