export const ActionTypes = {
    SET_SELECTED_PROJECT_ID: 'SET_SELECTED_PROJECT_ID',
    SET_SELECTED_PROJECT_RESOURCES: 'SET_SELECTED_PROJECT_RESOURCES',
    SET_SELECTED_PROJECT_REMAINING_BUDGET: 'SET_SELECTED_PROJECT_REMAINING_BUDGET',
    SET_SELECTED_PROJECT_VENDOR_ID: 'SET_SELECTED_PROJECT_VENDOR_ID',
    REMOVE_PROJECT_RESOURCE_BY_INDEX: 'REMOVE_PROJECT_RESOURCE_BY_INDEX',
};
