export const ErrorMessage = {
  TIMESHEET_ALREADY_INVOICED: "One or all of the timesheets in this invoice is already invoiced, so, please correct before updating.",
  INVOICE_TRANSACTION_FORM_ERROR: "All the fields are required.",
  INVOICE_TRANSACTION_ALREADY_PAID: "This invoice is completely paid or amount you entering is more than the total invoice amount, so no need for more payment.",
  INVOICE_EMAIL_TO_FORM_ERROR: "Email is required and should be valid.",
  SELECT_VENDOR_REQUIRED: "Please select a vendor.",
  SELECT_PROJECT_REQUIRED: "Please select a project.",
  SELECT_USER_REQUIRED: "Please select an user.",
  COMMENTS_REQUIRED: "Commets are required.",
  DAILY_NOTES_REQUIRED: "Daily notes are required for the selected project.",
  REPLY_REQUIRED: "Reply required.",
  COST_NAME_REQUIRED: "Please enter cost name to continue.",
  ERROR_UPLOADING: "Error uploading, please try again.",
  TIMESHEET_HOURS_ENTRY_ERROR: "Total hours for a day across multiple projects cannot be greater than 24. Please adjust accordingly.",
  VALUE_REQUIRED: "Value required, please enter.",
  ALL_FIELDS_REQIURED: "All the fields are required. Please enter and try again.",
  EXPENSE_TRANSACTION_FORM_ERROR: "All the fields are required.",
  INVOICE_TRANSACTION_ALREADY_PAID: "This expense is completely paid or amount you entering is more than the total expense amount, so no need for more payment.",
  TIMESHEET_PROJECT_BUDGET_ERROR_1: "Not enough budget available for the project: ",
  TIMESHEET_PROJECT_BUDGET_ERROR_2: ". You are over by ",
  TIMESHEET_PROJECT_BUDGET_ERROR_3: " hours. Please contact project administrator or adjust your hours accordingly.",
  SELECT_PROJECT_BEFORE_EXPENSE_ENTRY: "Please select a project before selecting an expense entry.",
  SELECT_RESOURCE_COST_ERROR: "Not able to add this expense type now.",
  INVALID_LOGON_CREDENTIALS: 'Invalid credentials. Please try again or reset password.',
  USER_NOT_ACTIVE: 'User is not active/approved, please contact administrator to unlock it.',
  ACCOUNT_NOT_ACTIVE: 'Account is not active/approved, please contact administrator to unlock it.',
  PASSWORD_CONFIRM_SAME: "Please enter password and confirm password and it matches.",
  ERROR_ADDING_NEW_ACCOUNT: "Error whild adding new account, Please try again or contact administrator.",
  USER_ALREADY_EXISTS: "Email ID already exists in our system, please try to login in or try to reset the password.",
}
