export const ErrorMessage = {
  TIMESHEET_ALREADY_INVOICED: "One or all of the timesheets in this invoice is already invoiced, so, please correct before updating.",
  INVOICE_TRANSACTION_FORM_ERROR: "All the fields are required.",
  INVOICE_TRANSACTION_ALREADY_PAID: "This invoice is completely paid or amount you entering is more than the total invoice amount, so no need for more payment.",
  INVOICE_EMAIL_TO_FORM_ERROR: "Email is required and should be valid.",
  SELECT_VENDOR_REQUIRED: "Please select a vendor.",
  SELECT_PROJECT_REQUIRED: "Please select a project.",
  SELECT_USER_REQUIRED: "Please select an user.",
  COMMENTS_REQUIRED: "Commers are required.",
  DAILY_NOTES_REQUIRED: "Daily notes are required for the selected project.",
  REPLY_REQUIRED: "Reply required.",
  ERROR_UPLOADING: "Error uploading, please try again.",
  TIMESHEET_HOURS_ENTRY_ERROR: "Total hours for a day across multiple projects cannot be greater than 24. Please adjust accordingly.",
  VALUE_REQUIRED: "Value required, please enter.",
  ALL_FIELDS_REQIURED: "All the fields are required.",
  EXPENSE_TRANSACTION_FORM_ERROR: "All the fields are required.",
  INVOICE_TRANSACTION_ALREADY_PAID: "This expense is completely paid or amount you entering is more than the total expense amount, so no need for more payment.",
  TIMESHEET_PROJECT_BUDGET_ERROR_1: "Not enough budget available for the project: ",
  TIMESHEET_PROJECT_BUDGET_ERROR_2: ". You are over by ",
  TIMESHEET_PROJECT_BUDGET_ERROR_3: " hours. Please contact project administrator or adjust your hours accordingly.",
  SELECT_PROJECT_BEFORE_EXPENSE_ENTRY: "Please select a project before selecting an expense entry.",
  SELECT_RESOURCE_COST_ERROR: "Not able to add this expense type now.",
}
