export const UserConstants = {
    SUPER_ADMIN_ID: '1',
    USER_ROLES:  { 
        SUPER_ADMIN: "SUPER_ADMIN",
        ACCOUNT_ADMIN: "ACCOUNT_ADMIN",
        ACCOUNT_VENDOR_REP: "ACCOUNT_VENDOR_REP",
        ACCOUNT_USER: "ACCOUNT_USER",
        ACCOUNT_VENDOR_EMPLOYEE: "ACCOUNT_VENDOR_EMPLOYEE",
        ACCOUNT_VENDOR_CONTRACTOR: "ACCOUNT_VENDOR_CONTRACTOR",
        ACCOUNT_MANAGER: "ACCOUNT_MANAGER",
        DEVELOPER: "DEVELOPER" 
    } 
}