export const ActionTypes = {
    SET_NOTES_BY_TYPE: 'SET_NOTES_BY_TYPE',
    GET_NOTES_BY_TYPE: 'GET_NOTES_BY_TYPE',
    RESET_NOTES_BY_TYPE: 'RESET_NOTES_BY_TYPE',
    SET_NOTES_TYPE: 'SET_NOTES_TYPE',
    GET_NOTES_TYPE: 'GET_NOTES_TYPE',
    RESET_NOTES_TYPE: 'RESET_NOTES_TYPE',
    SET_REPLIES: 'SET_REPLIES',
    GET_REPLIES: 'GET_REPLIES',
    RESET_REPLIES: 'RESET_REPLIES',
};
