export const ActionTypes = {
    SUBMIT_NEW_TIMESHEET: 'SUBMIT_NEW_TIMESHEET',
    SET_TIMESHEET_ENTRIES: 'SET_TIMESHEET_ENTRIES',
    GET_ALL_PROJECT_TIMESHEETS: 'GET_ALL_PROJECT_TIMESHEETS',
    GET_APPROVAL_TIMESHEETS: 'GET_APPROVAL_TIMESHEETS',
    REMOVE_UPDATED_TSE_FROM_APPROVAL_LIST: 'REMOVE_UPDATED_TSE_FROM_APPROVAL_LIST',
    SET_SELECTED_TIMESHEET_ID: 'SET_SELECTED_TIMESHEET_ID',
    SET_SELECTED_TIMESHEET_ENTRY_ID: 'SET_SELECTED_TIMESHEET_ENTRY_ID',
    SET_NEW_TS_WK_START_DIM_ID: 'SET_NEW_TS_WK_START_DIM_ID',
};
