export const ActionTypes = {
    SET_USER_VENDORS: 'SET_USER_VENDORS',
    GET_USER_VENDORS: 'GET_USER_VENDORS',
    RESET_USER_VENDORS: 'RESET_USER_VENDORS',
    ADD_USER_VENDOR: 'ADD_USER_VENDOR',
    REMOVE_USER_VENDOR_BY_INDEX: 'REMOVE_USER_VENDOR_BY_INDEX',
};
