export const ActionTypes = {
    SET_INVOICE_ITEM_LIST: 'SET_INVOICE_ITEM_LIST',
    RESET_INVOICE_ITEM_LIST: 'RESET_INVOICE_ITEM_LIST',
    REMOVE_ITEM_INVOICE_ITEM_LIST: 'REMOVE_ITEM_INVOICE_ITEM_LIST',
    SET_PROJECT_RESOURCES: 'SET_PROJECT_RESOURCES',
    RESET_PROJECT_RESOURCES: 'RESET_PROJECT_RESOURCES',
    SET_INVOICE_TOTAL: 'SET_INVOICE_TOTAL',
    REMOVE_TS_INVOICE_ITEM: 'REMOVE_TS_INVOICE_ITEM',

};
