export const ActionTypes = {
    SET_INVOICE_ITEM_LIST: 'SET_INVOICE_ITEM_LIST',
    RESET_INVOICE_ITEM_LIST: 'RESET_INVOICE_ITEM_LIST',
    REMOVE_ITEM_INVOICE_ITEM_LIST: 'REMOVE_ITEM_INVOICE_ITEM_LIST'


};
