export const ActionTypes = {
    SET_INVOICE_ITEM_LIST: 'SET_INVOICE_ITEM_LIST',
    RESET_INVOICE_ITEM_LIST: 'RESET_INVOICE_ITEM_LIST',
    REMOVE_ITEM_INVOICE_ITEM_LIST: 'REMOVE_ITEM_INVOICE_ITEM_LIST',
    SET_PROJECT_RESOURCES: 'SET_PROJECT_RESOURCES',
    RESET_PROJECT_RESOURCES: 'RESET_PROJECT_RESOURCES',
    SET_INVOICE_TOTAL: 'SET_INVOICE_TOTAL',
    REMOVE_TS_INVOICE_ITEM: 'REMOVE_TS_INVOICE_ITEM',
    INVOICE_PAID_AMOUNT: 'INVOICE_PAID_AMOUNT',
    GET_INVOICE_TRANSACTIONS: 'GET_INVOICE_TRANSACTIONS',
    SET_INVOICE_TRANSACTIONS: 'SET_INVOICE_TRANSACTIONS',
    UPDATE_INVOICE_TRANSACTIONS: 'UPDATE_INVOICE_TRANSACTIONS'
};
