export const ActionTypes = {
    SET_SELECTED_REPORTS_PROJECT_ID: 'SET_SELECTED_REPORTS_PROJECT_ID',
    SET_SELECTED_REPORTS_VENDOR_ID: 'SET_SELECTED_REPORTS_VENDOR_ID',
    SET_SELECTED_REPORTS_TAB_INDEX: 'SET_SELECTED_REPORTS_TAB_INDEX',
};
