export const ActionTypes = {
    SUBMIT_NEW_EXPENSE: 'SUBMIT_NEW_EXPENSE',
    SET_EXPENSE_ENTRIES: 'SET_EXPENSE_ENTRIES',
    GET_ALL_PROJECT_EXPENSES: 'GET_ALL_PROJECT_EXPENSES',
    GET_APPROVAL_EXPENSES: 'GET_APPROVAL_EXPENSES',
    REMOVE_UPDATED_TSE_FROM_APPROVAL_LIST: 'REMOVE_UPDATED_TSE_FROM_APPROVAL_LIST',
    SET_SELECTED_EXPENSE_ID: 'SET_SELECTED_EXPENSE_ID',
    SET_SELECTED_EXPENSE_ENTRY_ID: 'SET_SELECTED_EXPENSE_ENTRY_ID',
};
