export const ActionTypes = {
    SET_USERS_BY_ACCOUNT: 'SET_VENDORS_BY_ACCOUNT',
    GET_USERS_BY_ACCOUNT: 'GET_VENDORS_BY_ACCOUNT',
    RESET_USERS_BY_ACCOUNT: 'RESET_VENDORS_BY_ACCOUNT',
    SET_SELECTED_ACCOUNT_ID: 'SET_SELECTED_ACCOUNT_ID',
    RESET_SELECTED_ACCOUNT_ID: 'RESET_SELECTED_ACCOUNT_ID',
    SET_VENDORS_BY_ACCOUNT: 'SET_VENDORS_BY_ACCOUNT',
};
